### ISSUE TITLE
MULTI load

### ISSUE THREAD

**Issue by xillwillx** [marco-lancini/goscan#13]
when trying to load a text file with IPs it crashes on Kali
`[goscan] > load target MULTI re
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x740884]

goroutine 1 [running]:
github.com/marco-lancini/goscan/core/cli.cmdLoad(0xc420160210, 0x3, 0x3, 0x4)
        /go/src/github.com/marco-lancini/goscan/core/cli/executor.go:137 +0x114
github.com/marco-lancini/goscan/core/cli.Executor(0xc420096ce0, 0x14)
        /go/src/github.com/marco-lancini/goscan/core/cli/executor.go:23 +0x14e
github.com/marco-lancini/goscan/vendor/github.com/c-bata/go-prompt.(*Prompt).Run(0xc420255c20)
        /go/src/github.com/marco-lancini/goscan/vendor/github.com/c-bata/go-prompt/prompt.go:77 +0x688
main.main()
        /go/src/github.com/marco-lancini/goscan/main.go:67 +0xee`

**Comment by marco-lancini** [comment]
As per #11, did you provide the full path of your source file?

**Comment by xillwillx** [comment]
Tried full path also tried to put source in path of exe and broke on both

**Comment by marco-lancini** [comment]
Hi, when you mention `exe`, what kind of file are you trying to load?

**Comment by xillwillx** [comment]
sorry txt*
retried again tonight and got it working
