### ISSUE TITLE
Rate limit port scan?

### ISSUE THREAD

**Issue by friday963** [marco-lancini/goscan#20]
Hello, is there a switch that I can use to rate limit the number of concurrent scans that are done with the portscan flag?  I've loaded some 7 thousand IPs and its crashing every machine I run it from.  I've tried multiple times running this from screen on my droplet and I can't get the scan to finish.  I also am not recording any data it seems so even if it made it part way into the scan its not recording anything for me.

**Comment by marco-lancini** [comment]
Hi, rate limiting can be obtained directly from nmap and it is out of scope for goscan
