### ISSUE TITLE
Is this project abandoned? 

### ISSUE THREAD

**Issue by lnfjobs** [marco-lancini/goscan#21]
Cross compilation doesn't work on macosx.

Dep is deprecated and archived in favor of go modules. 

This project is actually not working (binary - executable) or compiling on go version go 1.16.3 darwin/amd64.

The biggest problems, requiring mod files (not as important as some think if you are compiling or running locally - compile and write your code in a way that it doesn't burden the end user - make this an option or remove), remove DEP, make all the fancy imports of the terminal colors and memory optional. This is killing it moving forward - unless you want people to use an old system just to get things to work.

**Comment by marco-lancini** [comment]
Hi @lnfjobs , thanks for creating this issue!
At the moment I don't have enough personal bandwidth to make the changes you suggested, but any help is welcomed!
