### ISSUE TITLE
Error - make setup

### ISSUE THREAD

**Issue by filebe777** [marco-lancini/goscan#7]
i got this error while setting up -

root@kali:~/goscan/goscan# make setup
go get github.com/golang/lint/golint
go get golang.org/x/tools/cmd/goimports
go get -u github.com/golang/dep/cmd/dep
dep ensure
could not find project Gopkg.toml, use dep init to initiate a manifest
make: *** [Makefile:13: setup] Error 1

when i tried second time - i got this error

root@kali:~/goscan/goscan# make setup
go get github.com/golang/lint/golint
go get golang.org/x/tools/cmd/goimports
go get -u github.com/golang/dep/cmd/dep
# cd /root/go/src/github.com/golang/dep; git pull --ff-only
fatal: unable to access 'https://github.com/golang/dep/': Could not resolve host: github.com
package github.com/golang/dep/cmd/dep: exit status 1
make: *** [Makefile:12: setup] Error 1

**Comment by marco-lancini** [comment]
Hi, are you trying to setup the development environment, or do you just want to use GoScan?
If it's the latter, you can just download the binary: https://github.com/marco-lancini/goscan#binary-installation-recommended

**Comment by filebe777** [comment]
I will like to use goscan in Kali linux

The error occurred while installing on Kali linux

Thanks for your response.
