### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by filebe777** [marco-lancini/goscan#8]
root@kali:~/Desktop/goscan/goscan# make setup
go get github.com/golang/lint/golint
go get golang.org/x/tools/cmd/goimports
go get -u github.com/golang/dep/cmd/dep
dep ensure
could not find project Gopkg.toml, use dep init to initiate a manifest
make: *** [Makefile:13: setup] Error 1

**Comment by marco-lancini** [comment]
Hi @filebe777, can you try add the following before line `13` of the `Makefile`:

```dep init```

Let me know if it works!

**Comment by hamperfait** [comment]
I think I might be able to help.

I was running into the same issue, so here is what I did:
```
go get -u github.com/marco-lancini/goscan
cd ~/go/src/github.com/marco-lancini/goscan
mv goscan goscan2
mv goscan2/goscan . && cd goscan
```
add dep init to makefile as @marco-lancini suggested, and finally
`make setup`

This worked for me, hope it helps

**Comment by SecureThisShit** [comment]
That didnt work for me:

go get github.com/golang/lint/golint
go get golang.org/x/tools/cmd/goimports
go get -u github.com/golang/dep/cmd/dep
dep init
init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/marco-lancini/goscan met constraints:
        v2.3: Could not introduce github.com/marco-lancini/goscan@v2.3 due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)        Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)
        v2.2: Could not introduce github.com/marco-lancini/goscan@v2.2 due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)     Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)
        v2.1: Could not introduce github.com/marco-lancini/goscan@v2.1 due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)     Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)       Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)   Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)
        v2.0: Could not introduce github.com/marco-lancini/goscan@v2.0 due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)        Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)
        v1.5: Could not introduce github.com/marco-lancini/goscan@v1.5 due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)        Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)
        v1.1: Could not introduce github.com/marco-lancini/goscan@v1.1 due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)        Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)
        v1.0: Could not introduce github.com/marco-lancini/goscan@v1.0 due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)       Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)   Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)       Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)   Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)
        master: Could not introduce github.com/marco-lancini/goscan@master due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)       Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)   Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)       Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)   Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)
        develop: Could not introduce github.com/marco-lancini/goscan@develop due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)        Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)
        untagged-2f2b1a79f9b471a127bf: Could not introduce github.com/marco-lancini/goscan@untagged-2f2b1a79f9b471a127bf due to multiple problematic subpackages:
        Subpackage github.com/marco-lancini/goscan/core/model is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/scan is missing. (Package is required by (root).)    Subpackage github.com/marco-lancini/goscan/core/utils is missing. (Package is required by (root).)      Subpackage github.com/marco-lancini/goscan/core/cli is missing. (Package is required by (root).)     Subpackage github.com/marco-lancini/goscan/core/enum is missing. (Package is required by (root).)
make: *** [Makefile:13: setup] Error 1

**Comment by hamperfait** [comment]
That is because you have to have the specified path: `$GOPATH/src/github.com/marco-lancini/goscan/core/`
You have to move the files from the folder because otherwise you have `$GOPATH/src/github.com/marco-lancini/goscan/goscan/core/`

**Comment by marco-lancini** [comment]
Hi everyone, I've updated the `README` file to simplify the process a little bit (without fiddling with folder names). 
I'm closing this for now, but feel free to reopen this issue if it still doesn't work for you.
